# Numpy

In [1]:
import numpy as np

### Reshaping (a,-1) returns flattened array

In [6]:
# reshaping (a,-1) returns the flattened array (one-dimensional), regardless of the initial shape.
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
b= a.reshape(-1)
b, b.shape

(matrix([[1, 2, 3, 4, 5, 6, 7, 8]]), (1, 8))

In [7]:
c= a.reshape(-1,1)
c,c.shape

(matrix([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]),
 (8, 1))

### np.take

In [3]:
# np.take will extract out the specific indices from a given list
np.take(['a', 'b', 'c', 'd', 'e', 'f'], [2,5,1])

array(['c', 'f', 'b'], dtype='<U1')

### np.newaxis

None is an alias for NP.newaxis. It creates an axis with length 1. This can be useful for matrix multiplcation etc.
label

The newaxis object can be used in all slicing operations to create an axis of length one. :const: newaxis is an alias for ‘None’, and ‘None’ can be used in place of this with the same result.

In [2]:
labels=np.array([1,3,5])

In [4]:
labels, labels.shape

(array([1, 3, 5]), (3,))

In [7]:
x = labels[:,None]

In [8]:
x.shape

(3, 1)

In [9]:
labels

array([1, 3, 5])

In [10]:
y = labels[:,np.newaxis]

In [11]:
y.shape

(3, 1)